[package]
name = "day3"
version = "0.1.0"
authors = ["Colin Bruner <colin.d.bruner@gmail.com>"]
edition = "2018"

write_mode = "overwrite"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
